language: objective-c 

osx_image: xcode10

matrix:
  include:
    - env: BUILD_CONFIG=Debug
    - env: BUILD_CONFIG=Release

script:
  - set -o pipefail && xcodebuild -configuration $BUILD_CONFIG | xcpretty

notifications:
  email: false
